#!/bin/bash

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias l='ls -h --file-type'
alias la='l -A'
alias ll='la -l'
alias lt='tree -aFL 2'
alias df='df -h'
alias pl='ps -eHo pid,tty,user,args'
alias p='pl c'
alias pt='pstree'
alias pa='pt -a'
alias bs="source ~/.bashrc"
alias git-include="git config --file ~/.config/gitinclude"
alias free="free -mt"
alias less=$PAGER
alias zless=$PAGER
alias xzless=$PAGER
alias bzless=$PAGER
alias lzless=$PAGER
alias st="screen-title"
alias tt="term-title"
alias screen="rm -f /var/run/utmp; screen -UDRR"
alias sudo="cygstart --action=runas"
vim_w3m() {
    vim -c ":W3m $@" 
}
alias w3m=vim_w3m

