#!/bin/bash

if ! [ -a "${SSH_AUTH_SOCK}" ]; then
    SSH_FIX_ENV="$HOME/.ssh-agent-fwd.`hostname`"

    if [ -f "${SSH_FIX_ENV}" ]; then
        . "${SSH_FIX_ENV}"
    fi
fi

# prompt colors
T_COLOR="\[\e[m\]"
F_COLOR="\[\e[33m\]"
W_COLOR="\[\e[m\]"
if [ "`id -u`" -eq 0 ]; then
    T_COLOR="\[\e[31m\]"
    F_COLOR="\[\e[35m\]"
else
    if [ -n "$VIM" ]; then
        T_COLOR="\[\e[32m\]"
        F_COLOR="\[\e[33m\]"
    fi
fi

if [ -O "${PWD}" ]; then
    W_COLOR="\[\e[34m\]"
else
    if [ -w "${PWD}" ]; then
        W_COLOR="\[\e[32m\]"
    fi
fi

