#!/bin/zsh

source "$HOME/.local/bin/xrandrout"

# xrdb
function get_xrdb() {
  xrdb -query | grep "$1" | awk '{print $2}' | tail -n1
}
xrdb -merge "${HOME}/.Xresources"

# pointer
xsetroot -cursor_name left_ptr

# border color
bspc config normal_border_color "$(get_xrdb background)"
bspc config focused_border_color "$(get_xrdb color12)"
bspc config border_width         3 
bspc config window_gap           0
bspc config split_ratio          0.50 
bspc config borderless_monocle   true 
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on 
bspc rule -a Dia state=floating 
bspc rule -a Ibus-extension-gtk3 state=floating 
bspc rule -a Pavucontrol state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a calfjackhost state=floating
bspc rule -a Calfjackhost state=floating
bspc rule -a "VMPK-Virtual MIDI Piano Keyboard" state=floating
bspc rule -a Galculator state=floating
bspc rule -a "-c" state=floating
bspc rule -a Rofi state=floating
bspc rule -a Zathura state=tiled

# compositor
compton -b

# polybar
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  MONITOR=$m polybar --reload archi3 &
done

# keybindings
sxhkd -m -1 &

if [ -e "$HOME/.tmpfs" ]; then
  lntmpfs
fi
# background image
if [ -e "$HOME/.fehbg" ]; then
  source "$HOME/.fehbg"
else
  feh --bg-tile "$HOME/Pictures/basket.png"
fi
numlockx on
if [ -e "$HOME/.bspwmrc_local" ]; then
  "$HOME/.bspwmrc_local"
fi
