#! /bin/bash

xrdb ~/.Xresources
if [ "$(systemd-detect-virt)" = "oracle" ]; then
  VBoxClient-all
fi
bspc monitor -d 0 1 2 3 4 5 6 7 8 9

function get_xrdb() {
  xrdb -query | grep "$1" | awk '{print $2}'
}

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "$(get_xrdb color9)"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Dia state=floating

polybar -r archi3 &
compton -b
sxhkd &

