export EDITOR="vim"
export VISUAL="vim"
export CM_LAUNCHER="rofi"
export TERMINAL=tilda
export GIT_EDITOR=$EDITOR
export LC_CTYPE=$LANG
export LC_NUMERIC=$LANG
export LC_TIME=$LANG
export LC_COLLATE="C"
export LC_MONETARY=$LANG
export LC_MESSAGES=$LANG
export LD_LIBRARY_PATH=.
export LESS="-erFX"
export DISABLE_AUTO_TITLE="true"
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
export QT_QPA_PLATFORMTHEME=qt5ct
